# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: devops-pool

stages:
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: BuildJob
    displayName: "Build Job"
    steps:
    - script: |
        echo "Executing Build Stage"
      displayName: "Echo Build Stage"

- stage: Test
  displayName: "Test Stage"
  dependsOn: Build
  jobs:
  - job: TestJob
    displayName: "Test Job"
    steps:
    - script: |
        echo "Executing Test Stage"
      displayName: "Echo Test Stage"

- stage: Deploy
  displayName: "Deploy Stage"
  dependsOn: Test
  jobs:
  - job: DeployJob
    displayName: "Deploy Job"
    steps:
    - script: |
        echo "Executing Deploy Stage"
      displayName: "Echo Deploy Stage"